development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:87ce036c7e131a93125f5ca24877f0c8@dory.redistogo.com:11826/
  channel_prefix: PanamaVenezuela_production
